version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "static-site-mail-server"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xv6ay08evutx"
s3_prefix = "static-site-mail-server"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
